<a href="https://colab.research.google.com/github/HrutikGujarkar/Neural-Network-and-deep-learningL-practical/blob/main/Practical1_NLDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
vector1=np.array([3,4,6,7,8])

In [ ]:
vector2=np.array([7,5,44,67,34])

In [ ]:
print(vector1)

[3 4 6 7 8]


In [ ]:
print(vector2)

[ 7  5 44 67 34]


In [ ]:
result=vector1+vector2
print(result)

[10  9 50 74 42]


In [ ]:
MatrixA=np.array([[2,4,5,6],[3,6,7,4],[35,7,8,6]])

In [ ]:
MatrixB=np.array([[2,4,5,8],[3,4,6,8],[9,2,5,9],[6,7,8,5]])

In [ ]:
print(MatrixA)

[[ 2  4  5  6]
 [ 3  6  7  4]
 [35  7  8  6]]


In [ ]:
print(MatrixB)

[[2 4 5 8]
 [3 4 6 8]
 [9 2 5 9]
 [6 7 8 5]]


In [ ]:
Matrix_Multiplication=np.matmul(MatrixA,MatrixB)

In [ ]:
print(Matrix_Multiplication)

[[ 97  76 107 123]
 [111  78 118 155]
 [199 226 305 438]]
